### ISSUE TITLE
Create a workflow for CI/CD pipeline for toPSAil

### ISSUE THREAD

**Issue by taehunk333** [taehunk333/toPSAil#21]
# Issue

As discussed in #20, missing automated tests are problematic when developers start to collaborate.

# Desired

Let's create a CI/CD pipeline for running our tests on a GitHub server, each time when we commit to a branch.

# Resources

This requires an active copy of MATLAB license; can we get this from Georgia Tech, @vajcsi? I am not sure if we need a dedicated license for the CI/CD pipeline.

# To Do

## 3. Add a GitHub Actions Workflow for CI
To integrate with GitHub, use GitHub Actions to set up CI for your MATLAB project. MATLAB provides a MATLAB GitHub Actions runner that allows you to test MATLAB code on GitHub's infrastructure.

Steps:

1. Create a GitHub Workflow File:

- In your repository, create the directory .github/workflows.
- Add a new file named matlab-ci.yml.

2. Define the Workflow: Add the following configuration to the file:

```
name: Run MATLAB Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: latest

    - name: Run Tests
      uses: matlab-actions/run-tests@v1
      with:
        sourceFolder: .
        testResultsJUnit: test-results/results.xml
        codeCoverageCobertura: code-coverage/coverage.xml
```

3. Explanation of Key Steps:

- checkout: Checks out your repository code into the GitHub runner.
- setup-matlab: Installs MATLAB on the runner (requires a MATLAB license; see [MATLAB on GitHub](https://github.com/matlab-actions)).
- run-tests: Runs the MATLAB tests and outputs results in formats like JUnit and Cobertura for integration with CI tools.

## 4. Add Test Results and Coverage Reports

1. Test Results: The matlab-actions/run-tests step generates JUnit test results (results.xml). GitHub Actions can display these results directly in the pull request checks.

2. Code Coverage:
- If you have a coverage tool set up in MATLAB, use codeCoverageCobertura to generate coverage reports.
- Add the coverage badge to your README.

## 5. Push and Verify
- Commit and push your matlab-ci.yml file and test files to the repository.
- Go to the Actions tab in your GitHub repository to monitor the workflow.
- On successful execution, you’ll see test results in your pull requests.
